- hosts: <your inventory group target here>
  tasks:
    - name: Install lynis
      become: yes
      become_method: sudo
      package:
        name: lynis
        state: present
    - name: Install aha
      become: yes
      become_method: sudo
      package:
        name: aha
        state: present
    - name: Ansible fact - ansible_date_time
      debug:
        var: ansible_date_time.date
    - name: Lynis audit system
      become: yes
      become_method: sudo
      shell: lynis audit system -Q | aha > /tmp/{{ansible_date_time.date}}@{{inventory_hostname}}.html
    - fetch:
        src: /tmp/{{ansible_date_time.date}}@{{inventory_hostname}}.html
        dest: /var/www/lynis/repots/{{ansible_date_time.date}}@{{inventory_hostname}}.html
        flat: yes
